export const ENVIRONMENT_SEEDS = [
  {
    id: 'epa-indoor-air', title: 'The Air Indoors Has Its Own Story', titleZh: '室内空气也有自己的故事', topic: '健康与环境', level: 'L2',
    source: ['U.S. Environmental Protection Agency', 'Introduction to Indoor Air Quality', 'https://www.epa.gov/indoor-air-quality-iaq/introduction-indoor-air-quality'],
    sentences: [
      'People spend much of their time indoors, where air can contain pollutants from many ordinary sources.',
      'Cooking, cleaning products, building materials, smoke, moisture, and outdoor pollution may all contribute.',
      'Poor ventilation can allow some pollutants to build up instead of moving outside.',
      'Opening windows may help in suitable conditions, but it is not always safe during smoke or heavy outdoor pollution.',
      'Source control, effective ventilation, moisture repair, and proper filtration work best as a combined strategy.',
      'A strong smell is not a reliable test because harmful pollutants can be odorless.',
      'Healthy indoor air depends on understanding the source before choosing the response.',
      'Small maintenance decisions can reduce exposure across the many hours people spend at home, school, or work.',
    ],
    guideZh: '记录污染来源，并注意开窗并非所有情况下都合适，解决方案需要因来源而异。',
    keyIdeaZh: '改善室内空气需要控制来源、通风、修复潮湿和过滤共同配合。',
    translationZh: '在烟雾或室外污染严重时，开窗并不总是安全的。',
    writingZh: '健康的室内空气取决于先了解污染来源。',
    speaking: 'Identify one indoor air source and suggest a practical way to reduce it.',
    vocab: [['ventilation', '/ˌventɪˈleɪʃn/', 'n.', '通风'], ['filtration', '/fɪlˈtreɪʃn/', 'n.', '过滤'], ['odorless', '/ˈoʊdərləs/', 'adj.', '无气味的']],
  },
  {
    id: 'epa-water-saving', title: 'Saving Water Begins with Finding Waste', titleZh: '节水从发现浪费开始', topic: '生活与环境', level: 'L1',
    source: ['U.S. Environmental Protection Agency', 'Start Saving', 'https://www.epa.gov/watersense/start-saving'],
    sentences: [
      'Water-saving advice often begins with shorter showers, but hidden leaks can waste water every day.',
      'A dripping faucet or running toilet may continue unnoticed because the loss happens slowly.',
      'Checking a water bill and meter can reveal changes that deserve investigation.',
      'Efficient fixtures reduce water use while still providing the service people need.',
      'Outdoor watering also deserves attention because plants, soil, weather, and season affect demand.',
      'Watering at the right time and repairing irrigation problems can prevent unnecessary loss.',
      'Conservation works best when people measure waste, fix it, and then improve daily habits.',
      'The goal is reliable service with less water, not simply using water as little as possible.',
    ],
    guideZh: '听出 detect、repair、improve 的行动顺序，并比较室内漏水与室外浇灌。',
    keyIdeaZh: '有效节水先找到持续浪费，再修复设备并调整习惯。',
    translationZh: '高效用水装置在提供人们所需服务的同时减少用水量。',
    writingZh: '节约在测量浪费之后效果最好。',
    speaking: 'Describe one way to detect wasted water at home before changing your habits.',
    vocab: [['fixture', '/ˈfɪkstʃər/', 'n.', '固定装置，用水器具'], ['irrigation', '/ˌɪrɪˈɡeɪʃn/', 'n.', '灌溉'], ['conservation', '/ˌkɑːnsərˈveɪʃn/', 'n.', '节约，保护']],
  },
  {
    id: 'epa-home-compost', title: 'Compost Turns Scraps into a Soil Resource', titleZh: '堆肥把厨余变成土壤资源', topic: '生活与环境', level: 'L1',
    source: ['U.S. Environmental Protection Agency', 'Composting at Home', 'https://www.epa.gov/recycle/composting-home'],
    sentences: [
      'Home composting uses natural decomposition to turn selected food and yard material into a soil amendment.',
      'A healthy pile needs a balance of nitrogen-rich green material and carbon-rich brown material.',
      'Air and moisture help microorganisms break material down without creating strong unpleasant odors.',
      'Fruit and vegetable scraps, dry leaves, and small plant pieces are common ingredients.',
      'Meat, dairy products, and greasy food may attract pests in a simple backyard system.',
      'Cutting material smaller and turning the pile can speed the process when conditions are suitable.',
      'Finished compost returns nutrients and organic matter to soil instead of sending useful material to a landfill.',
      'A good system depends on balance and observation rather than adding every kind of waste.',
    ],
    guideZh: '注意 green、brown、air、moisture 四个条件，并区分适合与不适合家庭堆肥的材料。',
    keyIdeaZh: '家庭堆肥靠材料、空气和水分的平衡，而不是把所有垃圾都放进去。',
    translationZh: '水果蔬菜残余、干叶和小块植物材料是常见原料。',
    writingZh: '成熟堆肥会把有机质送回土壤。',
    speaking: 'Explain what a beginner should add to a compost pile and what should stay out.',
    vocab: [['decomposition', '/ˌdiːkɑːmpəˈzɪʃn/', 'n.', '分解'], ['microorganism', '/ˌmaɪkroʊˈɔːrɡənɪzəm/', 'n.', '微生物'], ['amendment', '/əˈmendmənt/', 'n.', '土壤改良物']],
  },
  {
    id: 'epa-electronics-recycling', title: 'An Old Phone Is More Than Trash', titleZh: '旧手机不只是垃圾', topic: '科技与环境', level: 'L2',
    source: ['U.S. Environmental Protection Agency', 'Electronics Donation and Recycling', 'https://www.epa.gov/recycle/electronics-donation-and-recycling'],
    sentences: [
      'Electronic devices contain metals, glass, plastics, batteries, and components that require careful handling.',
      'A working device may serve someone else through reuse, repair, resale, or donation.',
      'Reusing equipment can extend its useful life before recycling becomes necessary.',
      'When a device reaches the end of that life, certified programs can recover material and manage hazards.',
      'Personal data should be backed up and removed before a phone or computer leaves its owner.',
      'Batteries may need a separate collection route because damage can create fire risks.',
      'The best choice follows a clear order: reduce unnecessary purchases, reuse safely, and recycle responsibly.',
      'Treating electronics as a resource protects information and materials at the same time.',
    ],
    guideZh: '按 reduce、reuse、recycle 的顺序听，并记录处理数据和电池时的特殊注意事项。',
    keyIdeaZh: '电子产品处理既关系材料回收，也关系个人数据和电池安全。',
    translationZh: '设备达到使用寿命终点后，合格项目可以回收材料并管理危险物。',
    writingZh: '最好的选择遵循清晰的顺序。',
    speaking: 'What steps should you take before giving an old phone to another person?',
    vocab: [['component', '/kəmˈpoʊnənt/', 'n.', '零部件'], ['certified', '/ˈsɜːrtɪfaɪd/', 'adj.', '经过认证的'], ['recover', '/rɪˈkʌvər/', 'v.', '回收，重新获得']],
  },
  {
    id: 'epa-stormwater-runoff', title: 'Rain Becomes a Problem When It Cannot Soak In', titleZh: '当雨水无法渗入土地时', topic: '气候与城市', level: 'L2',
    source: ['U.S. Environmental Protection Agency', 'Soak Up the Rain: What’s the Problem?', 'https://www.epa.gov/soakuptherain/soak-rain-whats-problem'],
    sentences: [
      'Rain that falls on roofs, roads, and parking lots cannot soak into the ground easily.',
      'It flows across hard surfaces, gathers oil, litter, soil, and other pollutants, and enters drains.',
      'Fast runoff can increase flooding, erode stream banks, and carry pollution into local water.',
      'Rain gardens, trees, permeable pavement, and rain barrels slow water or keep it on site.',
      'These approaches copy parts of the natural water cycle inside a developed neighborhood.',
      'No single practice fits every property because soil, space, rainfall, and maintenance differ.',
      'A city handles storms better when many small places absorb, store, and slow water together.',
      'The surface beneath a raindrop can shape its entire journey to a river or the ocean.',
    ],
    guideZh: '跟随一滴雨在硬化地面上的路径，并找出绿色设施怎样改变速度和去向。',
    keyIdeaZh: '许多分散的小型吸水和储水空间，可以共同降低城市雨洪风险。',
    translationZh: '雨水花园、树木、透水路面和雨水桶能够减缓水流或把水留在原地。',
    writingZh: '一座城市需要许多小地方共同减缓水流。',
    speaking: 'Choose one stormwater solution and explain where it could work in your neighborhood.',
    vocab: [['runoff', '/ˈrʌnɔːf/', 'n.', '地表径流'], ['permeable', '/ˈpɜːrmiəbl/', 'adj.', '可渗透的'], ['erode', '/ɪˈroʊd/', 'v.', '侵蚀']],
  },
  {
    id: 'epa-air-quality-index', title: 'One Number Can Guide a Health Decision', titleZh: '一个数字如何帮助健康决策', topic: '健康与环境', level: 'L2',
    source: ['AirNow', 'Air Quality Index Basics', 'https://www.airnow.gov/aqi/aqi-basics/'],
    sentences: [
      'The Air Quality Index translates measurements of common air pollutants into a scale people can use.',
      'Lower values generally indicate cleaner air, while higher values signal greater potential health concern.',
      'Colors and categories help communicate the meaning of a number quickly.',
      'Sensitive groups may need to reduce long or intense outdoor activity before everyone else does.',
      'The index can vary by pollutant, location, weather, smoke, traffic, and time of day.',
      'Checking a current local reading is therefore more useful than relying on yesterday’s conditions.',
      'The AQI does not remove pollution, but it helps people choose when and how to be active.',
      'Clear public information turns technical monitoring into a practical daily decision.',
    ],
    guideZh: '重点理解 AQI 如何把技术测量转化为颜色、类别和具体行动建议。',
    keyIdeaZh: '空气质量指数不能消除污染，但能帮助不同人群及时调整户外活动。',
    translationZh: '敏感人群可能需要比其他人更早减少长时间或高强度的户外活动。',
    writingZh: '当前的本地读数比昨天的情况更有用。',
    speaking: 'How would you change an outdoor plan if the AQI became unhealthy?',
    vocab: [['pollutant', '/pəˈluːtənt/', 'n.', '污染物'], ['sensitive', '/ˈsensətɪv/', 'adj.', '敏感的'], ['monitoring', '/ˈmɑːnɪtərɪŋ/', 'n.', '监测']],
  },
  {
    id: 'epa-wildfire-smoke', title: 'Wildfire Smoke Is a Mixture, Not a Single Gas', titleZh: '野火烟雾是混合物，不是单一气体', topic: '健康与环境', level: 'L3',
    source: ['U.S. Environmental Protection Agency', 'Why is Smoke a Health Concern?', 'https://www.epa.gov/wildfire-smoke-course/why-smoke-health-concern'],
    sentences: [
      'Wildfire smoke contains gases and fine particles produced as vegetation and other material burn.',
      'Fine particles are a major concern because they can travel deep into the lungs.',
      'Smoke concentration changes with fire behavior, wind, terrain, temperature, and distance.',
      'People with heart or lung conditions, older adults, children, and pregnant people may face greater risk.',
      'A building with closed windows is not automatically protected if outdoor smoke enters through leaks or ventilation.',
      'Air-quality information, cleaner indoor air, filtration, and reduced exposure can work together during an event.',
      'The safest response depends on current conditions and a person’s health rather than on smell alone.',
      'Understanding smoke as a changing mixture supports better choices before symptoms become severe.',
    ],
    guideZh: '听出烟雾成分、易感人群和降低暴露的多层策略，不要只用气味判断风险。',
    keyIdeaZh: '野火烟雾风险随环境和个人健康变化，需要结合监测、过滤与减少暴露。',
    translationZh: '患有心脏或肺部疾病的人、老年人、儿童和孕妇可能面临更高风险。',
    writingZh: '最安全的应对方式取决于当前条件和个人健康。',
    speaking: 'Give a simple plan for creating cleaner indoor air during a smoke event.',
    vocab: [['vegetation', '/ˌvedʒəˈteɪʃn/', 'n.', '植被'], ['concentration', '/ˌkɑːnsənˈtreɪʃn/', 'n.', '浓度'], ['exposure', '/ɪkˈspoʊʒər/', 'n.', '暴露']],
  },
  {
    id: 'epa-green-infrastructure', title: 'A City Can Work More Like a Watershed', titleZh: '城市也可以像流域一样工作', topic: '气候与城市', level: 'L3',
    source: ['U.S. Environmental Protection Agency', 'About Green Infrastructure', 'https://www.epa.gov/green-infrastructure/about-green-infrastructure'],
    sentences: [
      'Traditional drainage often moves stormwater away through pipes as quickly as possible.',
      'Green infrastructure manages some of that water where it falls by using plants, soil, and permeable surfaces.',
      'Examples include rain gardens, green roofs, street trees, restored wetlands, and connected open space.',
      'These systems can reduce runoff while also cooling streets, supporting habitat, and improving public space.',
      'They still require design, inspection, and maintenance rather than functioning as decoration alone.',
      'Engineers may combine green features with conventional pipes when storms exceed local storage capacity.',
      'Resilient infrastructure uses several layers so the failure of one layer does not become a complete failure.',
      'Managing rain as a resource can create benefits beyond the original drainage problem.',
    ],
    guideZh: '比较传统管道与绿色基础设施，并记录后者除了排水之外带来的共同收益。',
    keyIdeaZh: '绿色基础设施在雨水落下处管理它，并与传统工程共同形成多层韧性。',
    translationZh: '这些系统能减少径流，同时给街道降温、支持栖息地并改善公共空间。',
    writingZh: '有韧性的基础设施会使用多个层次。',
    speaking: 'Which green infrastructure feature would bring the most benefits to a dense city street?',
    vocab: [['infrastructure', '/ˈɪnfrəstrʌktʃər/', 'n.', '基础设施'], ['conventional', '/kənˈvenʃənl/', 'adj.', '传统的'], ['resilient', '/rɪˈzɪliənt/', 'adj.', '有韧性的']],
  },
  {
    id: 'epa-lead-exposure', title: 'Lead Risk Depends on Contact, Not Appearance', titleZh: '铅风险取决于接触，而不是外观', topic: '健康与环境', level: 'L3',
    source: ['U.S. Environmental Protection Agency', 'Learn About Lead', 'https://www.epa.gov/lead/learn-about-lead'],
    sentences: [
      'Lead is a naturally occurring metal that was widely used in paint, fuel, plumbing, and many products.',
      'Old paint can create contaminated dust when it peels or is disturbed during renovation.',
      'Lead may also enter drinking water when plumbing materials corrode under certain conditions.',
      'Children are especially vulnerable because exposure can affect the developing brain and nervous system.',
      'A surface or glass of water may look normal even when testing detects lead.',
      'Safe renovation, proper cleaning, certified testing, and attention to water systems reduce risk.',
      'Prevention depends on identifying likely sources before work or exposure spreads contamination.',
      'An invisible hazard requires evidence-based testing rather than confidence based on appearance.',
    ],
    guideZh: '抓住 paint dust、plumbing、testing 三条线索，理解为什么看起来正常不能排除风险。',
    keyIdeaZh: '铅污染往往不可见，预防需要识别来源、规范操作和检测证据。',
    translationZh: '儿童尤其脆弱，因为接触铅可能影响正在发育的大脑和神经系统。',
    writingZh: '无形的危险需要以证据为基础的检测。',
    speaking: 'Why is visual inspection not enough when checking for possible lead exposure?',
    vocab: [['corrode', '/kəˈroʊd/', 'v.', '腐蚀'], ['vulnerable', '/ˈvʌlnərəbl/', 'adj.', '易受伤害的'], ['contamination', '/kənˌtæmɪˈneɪʃn/', 'n.', '污染']],
  },
]
