export const HEALTH_SEEDS = [
  {
    id: 'cdc-sleep-routine', title: 'Good Sleep Starts Before Bedtime', titleZh: '好睡眠从上床之前开始', topic: '健康与日常', level: 'L1',
    source: ['Centers for Disease Control and Prevention', 'About Sleep', 'https://www.cdc.gov/sleep/about/index.html'],
    sentences: [
      'Sleep supports attention, mood, memory, physical health, and the body’s ability to recover.',
      'A regular schedule helps the brain connect a familiar time with rest.',
      'Bright light, caffeine, heavy meals, and stimulating activity late in the day may delay sleep.',
      'A quiet, dark, cool room can make the sleep environment more comfortable.',
      'Weekend schedules that shift dramatically may make Monday morning feel like another time zone.',
      'A useful routine begins with a consistent wake time and small evening signals that can be repeated.',
      'Better sleep is usually built through daily patterns rather than one perfect night.',
      'Persistent sleep problems deserve professional attention instead of endless self-experimenting.',
    ],
    guideZh: '听出 schedule、environment 和 evening signals 三组习惯，并注意何时应寻求专业帮助。',
    keyIdeaZh: '睡眠质量更依赖可重复的日常规律，而不是偶尔的一晚完美睡眠。',
    translationZh: '安静、黑暗、凉爽的房间能让睡眠环境更加舒适。',
    writingZh: '有用的习惯始于稳定的起床时间。',
    speaking: 'Describe one evening habit that helps sleep and one habit that may delay it.',
    vocab: [['stimulating', '/ˈstɪmjuleɪtɪŋ/', 'adj.', '使兴奋的'], ['persistent', '/pərˈsɪstənt/', 'adj.', '持续的'], ['recover', '/rɪˈkʌvər/', 'v.', '恢复']],
  },
  {
    id: 'cdc-clean-hands', title: 'Clean Hands Need More Than a Quick Rinse', titleZh: '清洁双手不只是快速冲水', topic: '健康与日常', level: 'L1',
    source: ['Centers for Disease Control and Prevention', 'About Hand Hygiene in Schools and Early Care', 'https://www.cdc.gov/clean-hands/about/index.html'],
    sentences: [
      'Hands touch shared surfaces, food, faces, and other people throughout an ordinary day.',
      'Washing with soap and clean running water removes germs and material that can carry them.',
      'Scrubbing all hand surfaces for about twenty seconds gives the process time to work.',
      'Thumbs, fingertips, the backs of hands, and spaces between fingers are easy to miss.',
      'Hands should be dried because germs transfer more easily to and from wet skin.',
      'Alcohol-based sanitizer is useful when soap and water are unavailable, but it does not remove every kind of contamination.',
      'Good technique matters more than making the washing routine look fast or impressive.',
      'Regular hand hygiene is a simple layer of protection, especially before food and after possible exposure.',
    ],
    guideZh: '按 wet、soap、scrub、rinse、dry 的顺序理解步骤，并找出容易遗漏的位置。',
    keyIdeaZh: '洗手效果取决于肥皂、时间、覆盖范围和干燥，而不是简单冲一下。',
    translationZh: '拇指、指尖、手背和手指之间的缝隙很容易被忽略。',
    writingZh: '正确的方法比快速完成更重要。',
    speaking: 'Explain the handwashing steps to someone who usually rinses for only a few seconds.',
    vocab: [['scrub', '/skrʌb/', 'v.', '用力擦洗'], ['fingertip', '/ˈfɪŋɡərtɪp/', 'n.', '指尖'], ['sanitizer', '/ˈsænɪtaɪzər/', 'n.', '消毒剂']],
  },
  {
    id: 'cdc-food-safety', title: 'Four Actions Make Food Safer', titleZh: '四个动作让食物更安全', topic: '健康与日常', level: 'L1',
    source: ['Centers for Disease Control and Prevention', 'About Four Steps to Food Safety', 'https://www.cdc.gov/food-safety/prevention/index.html'],
    sentences: [
      'Food safety at home can be organized around four actions: clean, separate, cook, and chill.',
      'Cleaning removes germs from hands, tools, and surfaces before they spread.',
      'Separating raw meat from ready-to-eat food reduces cross-contamination.',
      'Cooking to a safe internal temperature requires a food thermometer rather than guessing from color.',
      'Chilling food promptly slows the growth of many harmful germs.',
      'The refrigerator should keep food cold, but it does not make unsafe food safe again.',
      'Each action blocks a different path by which germs can reach or multiply in a meal.',
      'A simple sequence is easier to remember and repeat than a long list of disconnected warnings.',
    ],
    guideZh: '记住 clean、separate、cook、chill，并说明每一步阻断了哪一种风险。',
    keyIdeaZh: '四个动作分别控制传播、交叉污染、加热不足和细菌繁殖。',
    translationZh: '烹饪到安全的内部温度需要食物温度计，而不是凭颜色猜测。',
    writingZh: '每个动作都阻断了不同的风险路径。',
    speaking: 'Use the four food-safety actions to describe how you would prepare a meal.',
    vocab: [['cross-contamination', '/ˌkrɔːs kənˌtæmɪˈneɪʃn/', 'n.', '交叉污染'], ['thermometer', '/θərˈmɑːmɪtər/', 'n.', '温度计'], ['promptly', '/ˈprɑːmptli/', 'adv.', '迅速地']],
  },
  {
    id: 'cdc-vaccines-memory', title: 'Vaccines Train Immune Memory', titleZh: '疫苗训练免疫记忆', topic: '健康与科学', level: 'L2',
    source: ['Centers for Disease Control and Prevention', 'Explaining How Vaccines Work', 'https://www.cdc.gov/vaccines/basics/explaining-how-vaccines-work.html'],
    sentences: [
      'The immune system recognizes germs, responds to them, and can remember parts of that encounter.',
      'Vaccines present a safe signal that helps the body practice a protective response.',
      'Different vaccine technologies deliver that signal in different ways without needing the full disease experience.',
      'After vaccination, immune memory can respond faster if the actual germ appears later.',
      'Protection may take time to develop, and some vaccines require more than one dose or a later booster.',
      'No medical product removes every risk, so recommendations weigh benefits, known effects, and disease danger.',
      'Vaccination turns preparation into an advantage before the body faces a real infection.',
      'Clear explanations should distinguish temporary immune responses from the illness a vaccine is designed to prevent.',
    ],
    guideZh: '围绕 signal、practice、memory、faster response 理解疫苗原理，不把训练反应等同于患病。',
    keyIdeaZh: '疫苗让免疫系统提前练习并形成记忆，以便更快应对真实病原体。',
    translationZh: '接种后，如果真正的病原体后来出现，免疫记忆可以更快作出反应。',
    writingZh: '疫苗把提前准备变成了一种优势。',
    speaking: 'Explain immune memory with a simple comparison that avoids saying a vaccine causes the full disease.',
    vocab: [['immune', '/ɪˈmjuːn/', 'adj.', '免疫的'], ['booster', '/ˈbuːstər/', 'n.', '加强针'], ['encounter', '/ɪnˈkaʊntər/', 'n.', '遭遇']],
  },
  {
    id: 'cdc-healthy-weight', title: 'Health Is a Pattern, Not a Single Number', titleZh: '健康是一种长期模式，不是单一数字', topic: '健康与日常', level: 'L2',
    source: ['Centers for Disease Control and Prevention', 'About Healthy Weight and Growth', 'https://www.cdc.gov/healthy-weight-growth/about/index.html'],
    sentences: [
      'Body weight can provide useful health information, but it never describes a whole person by itself.',
      'Sleep, food, movement, stress, medicine, genetics, environment, and life stage can all influence weight.',
      'Fast changes may be difficult to maintain and can distract from behaviors that support long-term health.',
      'Regular meals, varied food, enjoyable activity, and enough rest create a more practical foundation.',
      'A healthcare professional can interpret measurements inside an individual medical context.',
      'Respectful goals focus on health and function rather than shame or unrealistic comparison.',
      'A sustainable pattern is more informative than one isolated number on one morning.',
      'Progress can include energy, strength, sleep, laboratory results, and habits as well as weight.',
    ],
    guideZh: '注意文章如何限制单一体重数字的意义，并列出更全面的进步指标。',
    keyIdeaZh: '体重需要放在个人健康背景中理解，长期行为模式比孤立数字更重要。',
    translationZh: '规律饮食、多样食物、愉快运动和充足休息构成了更实际的基础。',
    writingZh: '可持续的模式比一个孤立数字更有信息量。',
    speaking: 'Name two ways to measure health progress without focusing only on body weight.',
    vocab: [['genetics', '/dʒəˈnetɪks/', 'n.', '遗传因素'], ['sustainable', '/səˈsteɪnəbl/', 'adj.', '可持续的'], ['isolated', '/ˈaɪsəleɪtɪd/', 'adj.', '孤立的']],
  },
  {
    id: 'cdc-mental-health', title: 'Mental Health Changes and Can Be Supported', titleZh: '心理健康会变化，也可以得到支持', topic: '心理与社会', level: 'L2',
    source: ['Centers for Disease Control and Prevention', 'About Mental Health', 'https://www.cdc.gov/mental-health/about/index.html'],
    sentences: [
      'Mental health includes emotional, psychological, and social well-being across everyday life.',
      'It can influence how people handle stress, build relationships, make decisions, and care for themselves.',
      'Everyone experiences difficult emotions, but duration, intensity, and impact help show when more support is needed.',
      'Sleep, movement, connection, meaningful activity, and professional care can all play useful roles.',
      'Reaching out early may prevent a manageable problem from becoming a crisis.',
      'Support should be practical and respectful rather than reducing a person to a diagnosis.',
      'Mental health is not a permanent label; it can change with circumstances, treatment, and time.',
      'In an immediate danger or crisis, urgent local professional help is more appropriate than general self-care advice.',
    ],
    guideZh: '区分普通困难情绪与需要更多支持的信号，并注意文章对危机情况的边界说明。',
    keyIdeaZh: '心理健康会随环境和时间变化，及时、尊重且适当的支持很重要。',
    translationZh: '每个人都会经历困难情绪，但持续时间、强度和影响能帮助判断何时需要更多支持。',
    writingZh: '及早求助可能防止问题演变成危机。',
    speaking: 'What is one respectful way to offer support without trying to diagnose someone?',
    vocab: [['well-being', '/ˌwel ˈbiːɪŋ/', 'n.', '身心健康'], ['intensity', '/ɪnˈtensəti/', 'n.', '强度'], ['diagnosis', '/ˌdaɪəɡˈnoʊsɪs/', 'n.', '诊断']],
  },
  {
    id: 'cdc-sun-safety', title: 'Sun Protection Works in Layers', titleZh: '防晒需要多层保护', topic: '健康与日常', level: 'L1',
    source: ['Centers for Disease Control and Prevention', 'Sun Safety Facts', 'https://www.cdc.gov/skin-cancer/sun-safety/index.html'],
    sentences: [
      'Ultraviolet radiation from the Sun can damage skin even when the weather does not feel very hot.',
      'Clouds may reduce some sunlight, but they do not remove all ultraviolet exposure.',
      'Shade, protective clothing, a hat, sunglasses, and sunscreen provide different layers of protection.',
      'Sunscreen should cover exposed skin and be reapplied according to its directions, especially after water or sweating.',
      'Midday sunlight is often stronger, so timing can reduce exposure during long outdoor activities.',
      'Children and adults both benefit from habits that do not depend on noticing a burn first.',
      'No single layer is perfect, but several practical layers reduce total exposure.',
      'Sun safety supports outdoor activity instead of requiring people to avoid the outdoors completely.',
    ],
    guideZh: '找出 shade、clothing、sunscreen、timing 四层保护，并注意紫外线与温度不同。',
    keyIdeaZh: '防晒不是依赖单一产品，而是把遮阴、衣物、防晒霜和时间安排结合起来。',
    translationZh: '防晒霜应覆盖暴露的皮肤，并按说明重新涂抹，尤其是在接触水或出汗之后。',
    writingZh: '多个实际的保护层可以减少总暴露。',
    speaking: 'Plan sun protection for a two-hour outdoor activity using at least three layers.',
    vocab: [['ultraviolet', '/ˌʌltrəˈvaɪələt/', 'adj.', '紫外线的'], ['reapply', '/ˌriːəˈplaɪ/', 'v.', '再次涂抹'], ['exposure', '/ɪkˈspoʊʒər/', 'n.', '暴露']],
  },
  {
    id: 'cdc-antibiotic-use', title: 'Antibiotics Treat Bacteria, Not Every Infection', titleZh: '抗生素治疗细菌，而不是所有感染', topic: '健康与科学', level: 'L2',
    source: ['Centers for Disease Control and Prevention', 'Antibiotic Use and Antimicrobial Resistance Facts', 'https://www.cdc.gov/antibiotic-use/about/index.html'],
    sentences: [
      'Antibiotics are medicines designed to treat certain infections caused by bacteria.',
      'They do not treat viruses such as those that cause colds or influenza.',
      'Using an antibiotic when it is not needed can cause side effects without helping the illness.',
      'It can also contribute to antimicrobial resistance, which makes some germs harder to treat later.',
      'The correct drug, dose, and duration depend on the infection and a clinician’s judgment.',
      'People should not save leftover antibiotics, share them, or demand them for every respiratory symptom.',
      'Responsible use protects the current patient while preserving treatment options for other people.',
      'Good medical care sometimes means receiving symptom relief and advice instead of an antibiotic prescription.',
    ],
    guideZh: '听清 bacteria 与 virus 的区别，并理解个人用药如何影响未来治疗选择。',
    keyIdeaZh: '只在需要时正确使用抗生素，既保护当前患者，也减缓耐药性。',
    translationZh: '不需要时使用抗生素可能带来副作用，却无法帮助治疗疾病。',
    writingZh: '负责任的使用能够保留未来的治疗选择。',
    speaking: 'Explain why not receiving an antibiotic can sometimes be the correct medical decision.',
    vocab: [['antibiotic', '/ˌæntibaɪˈɑːtɪk/', 'n.', '抗生素'], ['resistance', '/rɪˈzɪstəns/', 'n.', '耐药性'], ['prescription', '/prɪˈskrɪpʃn/', 'n.', '处方']],
  },
  {
    id: 'cdc-hearing-protection', title: 'Hearing Damage Can Build Quietly', titleZh: '听力损伤可能在无声中累积', topic: '健康与日常', level: 'L2',
    source: ['Centers for Disease Control and Prevention', 'About Noise-Induced Hearing Loss', 'https://www.cdc.gov/hearing-loss/about/index.html'],
    sentences: [
      'Very loud sound can damage sensitive structures in the inner ear in a short time.',
      'Lower sound levels may also cause harm when exposure continues for long periods or happens repeatedly.',
      'Pain is not a reliable warning because damaging sound may not feel painful in the moment.',
      'Distance, time, volume, and hearing protection all change the amount of sound energy reaching the ear.',
      'Moving away from speakers, taking quiet breaks, lowering volume, and using well-fitted protection reduce risk.',
      'Temporary ringing or muffled hearing after noise is a sign that the ears were stressed.',
      'Protective habits work best before a permanent change becomes noticeable.',
      'Enjoying music, tools, or events safely means managing exposure rather than waiting for discomfort.',
    ],
    guideZh: '抓住 volume、time、distance、protection 四个变量，理解“没有疼痛”不等于安全。',
    keyIdeaZh: '噪声风险由音量和暴露时间共同决定，保护必须发生在永久损伤之前。',
    translationZh: '距离、时间、音量和听力保护都会改变到达耳朵的声能。',
    writingZh: '保护习惯应该在永久变化出现之前建立。',
    speaking: 'How would you protect your hearing at a loud concert or while using power tools?',
    vocab: [['muffled', '/ˈmʌfld/', 'adj.', '声音沉闷的'], ['exposure', '/ɪkˈspoʊʒər/', 'n.', '暴露'], ['permanent', '/ˈpɜːrmənənt/', 'adj.', '永久的']],
  },
]
