export const OCEAN_SEEDS = [
  {
    id: 'noaa-marine-debris', title: 'Marine Debris Begins Far from the Ocean', titleZh: '海洋垃圾可能从离海很远的地方开始', topic: '海洋与环境', level: 'L2',
    source: ['NOAA National Ocean Service', 'What is marine debris?', 'https://oceanservice.noaa.gov/facts/marinedebris.html'],
    sentences: [
      'Marine debris includes persistent manufactured material that is abandoned in oceans, coasts, or the Great Lakes.',
      'Fishing gear, plastic packaging, bottles, and many other objects can injure wildlife or obstruct navigation.',
      'Much of this debris begins on land rather than being dropped directly from a boat.',
      'Rain and wind can move litter into storm drains, rivers, and eventually coastal water.',
      'Once debris enters a current, it may travel long distances and become difficult to recover.',
      'Prevention therefore includes secure waste systems, careful recreation, and reducing disposable items.',
      'A local action can matter because water connects streets and rivers with the wider ocean.',
      'Cleanup is useful, but stopping material before it escapes is usually more efficient.',
    ],
    guideZh: '听清垃圾从 land 到 storm drain、river、ocean 的移动路径，并比较清理与预防。',
    keyIdeaZh: '街道、河流和海洋由水相连，因此海洋垃圾预防必须从陆地开始。',
    translationZh: '雨水和风会把垃圾带入雨水排水沟、河流，并最终带到沿海水域。',
    writingZh: '一个地方的行动也可能产生影响。',
    speaking: 'Name one item that could become marine debris and explain how to prevent it.',
    vocab: [['debris', '/dəˈbriː/', 'n.', '碎片，垃圾'], ['obstruct', '/əbˈstrʌkt/', 'v.', '阻碍'], ['disposable', '/dɪˈspoʊzəbl/', 'adj.', '一次性的']],
  },
  {
    id: 'noaa-ocean-gyres', title: 'A Gyre Moves More Than Water', titleZh: '海洋环流带走的不只是海水', topic: '海洋与环境', level: 'L2',
    source: ['NOAA National Ocean Service', 'What is a gyre?', 'https://oceanservice.noaa.gov/facts/gyre.html'],
    sentences: [
      'A gyre is a large system of rotating ocean currents rather than a single floating island of trash.',
      'Wind, tides, Earth’s rotation, temperature, and salinity all help drive movement in the ocean.',
      'Five major subtropical gyres organize broad patterns across the Atlantic, Pacific, and Indian Oceans.',
      'These currents transport heat, nutrients, ships, organisms, and pollution over long distances.',
      'Floating debris can gather in some regions, which is why gyres are often associated with garbage patches.',
      'However, most debris remains spread through a huge area instead of forming a solid surface.',
      'Accurate language matters because a moving current system is not the same as a permanent trash island.',
      'Current data supports navigation, rescue work, environmental response, and scientific forecasting.',
    ],
    guideZh: '区分 gyre 和 garbage patch，记录海流的驱动力以及它能运输的不同事物。',
    keyIdeaZh: '环流是庞大的动态海流系统，垃圾只是它可能运输和聚集的物质之一。',
    translationZh: '这些海流会把热量、营养物、船只、生物和污染物带到很远的地方。',
    writingZh: '准确的语言很重要。',
    speaking: 'Why is it misleading to describe a gyre as a solid island of trash?',
    vocab: [['gyre', '/ˈdʒaɪər/', 'n.', '海洋环流'], ['salinity', '/səˈlɪnəti/', 'n.', '盐度'], ['forecasting', '/ˈfɔːrkæstɪŋ/', 'n.', '预测']],
  },
  {
    id: 'noaa-tides-gravity', title: 'Tides Are a Pattern, Not a Fixed Schedule', titleZh: '潮汐有规律，却不是固定时刻表', topic: '海洋与环境', level: 'L2',
    source: ['NOAA National Ocean Service', 'What are tides?', 'https://oceanservice.noaa.gov/facts/tides.html'],
    sentences: [
      'Tides are long-period waves that cause ocean levels to rise and fall along coasts.',
      'The gravitational pull of the Moon has the strongest influence, while the Sun also contributes.',
      'Coastline shape, water depth, and local geography change how that astronomical force appears in each place.',
      'Some locations experience two similar high tides each day, while others follow different patterns.',
      'Weather can push water above or below the level predicted from gravity alone.',
      'For this reason, tide tables are local forecasts rather than universal daily schedules.',
      'Boaters, coastal workers, scientists, and visitors all use tide information to plan safely.',
      'A predictable natural cycle still requires local measurements and current weather knowledge.',
    ],
    guideZh: '先听引力造成的总体规律，再找出海岸形状、水深和天气如何改变当地潮位。',
    keyIdeaZh: '天体引力形成潮汐规律，但当地地形和天气决定具体表现。',
    translationZh: '有些地方每天出现两次相似的高潮，而其他地方遵循不同模式。',
    writingZh: '潮汐表是地方性预测，而不是全球统一的时间表。',
    speaking: 'Why should someone check a local tide table instead of using a general rule?',
    vocab: [['gravitational', '/ˌɡrævɪˈteɪʃənl/', 'adj.', '引力的'], ['astronomical', '/ˌæstrəˈnɑːmɪkl/', 'adj.', '天文的'], ['predicted', '/prɪˈdɪktɪd/', 'adj.', '预测的']],
  },
  {
    id: 'noaa-ocean-blue', title: 'Why the Ocean Often Looks Blue', titleZh: '海洋为什么常常呈现蓝色', topic: '海洋与环境', level: 'L1',
    source: ['NOAA National Ocean Service', 'Why is the ocean blue?', 'https://oceanservice.noaa.gov/facts/oceanblue.html'],
    sentences: [
      'Ocean color begins with the way water absorbs and scatters different parts of visible light.',
      'Water absorbs colors near the red end of the spectrum more readily than blue light.',
      'More blue light remains available to scatter back toward an observer’s eyes.',
      'The sky can reflect on the surface, but reflection is not the main reason deep water looks blue.',
      'Sediment, algae, depth, clouds, and the angle of sunlight can all change the color we see.',
      'Green or brown water is therefore not simply a failure to reflect a blue sky.',
      'Ocean color carries information about water, particles, and living organisms below the surface.',
      'Satellites use these color differences to help scientists monitor large marine regions.',
    ],
    guideZh: '重点区分 absorb、scatter 和 reflect，避免把海洋颜色简单解释成天空倒影。',
    keyIdeaZh: '海水对不同波长光的吸收和散射，是深水常呈蓝色的主要原因。',
    translationZh: '天空会倒映在海面上，但倒影并不是深水呈蓝色的主要原因。',
    writingZh: '海洋颜色携带着水面以下的信息。',
    speaking: 'Explain why ocean water can look green or brown instead of blue.',
    vocab: [['absorb', '/əbˈzɔːrb/', 'v.', '吸收'], ['scatter', '/ˈskætər/', 'v.', '散射'], ['sediment', '/ˈsedɪmənt/', 'n.', '沉积物']],
  },
  {
    id: 'noaa-ocean-salt', title: 'Rivers Carry the Ingredients of a Salty Ocean', titleZh: '河流把海洋盐分的原料带入大海', topic: '海洋与环境', level: 'L2',
    source: ['NOAA National Ocean Service', 'Why is the ocean salty?', 'https://oceanservice.noaa.gov/facts/whysalty.html'],
    sentences: [
      'Rainwater reacts with carbon dioxide in the air and becomes slightly acidic.',
      'As it moves across rocks and soil, it dissolves small amounts of minerals and salts.',
      'Rivers carry many of those dissolved materials toward the ocean over long periods.',
      'Water also enters and leaves the seafloor through hydrothermal systems that exchange minerals.',
      'Ocean water evaporates, but most dissolved salts remain behind and become concentrated.',
      'The process continues slowly across geological time rather than during one dramatic event.',
      'Rivers taste fresh because their salt concentration is far lower than the concentration in seawater.',
      'The salty ocean records a long interaction among rain, rock, rivers, seafloor, and evaporation.',
    ],
    guideZh: '按 rain、rock、river、ocean、evaporation 的顺序复述盐分长期积累的过程。',
    keyIdeaZh: '海洋盐分来自水、岩石和海底长期交换，蒸发又让盐分留在海中。',
    translationZh: '水还会通过热液系统进出海底，并在这个过程中交换矿物质。',
    writingZh: '这个过程在地质时间里缓慢持续。',
    speaking: 'Describe the journey of one dissolved mineral from rock to the ocean.',
    vocab: [['acidic', '/əˈsɪdɪk/', 'adj.', '酸性的'], ['dissolve', '/dɪˈzɑːlv/', 'v.', '溶解'], ['hydrothermal', '/ˌhaɪdroʊˈθɜːrml/', 'adj.', '热液的']],
  },
  {
    id: 'noaa-rip-current', title: 'A Rip Current Pulls Away, Not Under', titleZh: '离岸流把人带离岸边，而不是拖入水下', topic: '安全与自然', level: 'L1',
    source: ['NOAA National Ocean Service', 'What is a rip current?', 'https://oceanservice.noaa.gov/facts/ripcurrent.html'],
    sentences: [
      'A rip current is a narrow, fast-moving channel of water that flows away from the shore.',
      'It does not pull a swimmer under the water, but it can carry someone farther offshore.',
      'Trying to swim directly against the current may cause exhaustion and panic.',
      'A safer response is to stay calm, float, signal for help, and move parallel to the beach when possible.',
      'Rip currents can appear near breaks in sandbars, structures, or places where waves return seaward.',
      'Conditions change quickly, so even experienced swimmers should respect warnings and lifeguard advice.',
      'Knowing the direction of the current helps replace a dangerous struggle with a planned escape.',
      'Beach safety begins before entering the water by checking conditions and choosing a guarded area.',
    ],
    guideZh: '这是安全类内容，请听清错误动作、正确动作以及 parallel to the beach 的方向。',
    keyIdeaZh: '遇到离岸流时不要逆流硬游，应保持冷静、漂浮并尝试平行海岸移动。',
    translationZh: '更安全的做法是保持冷静、漂浮、发出求救信号，并在可能时平行海滩移动。',
    writingZh: '了解水流方向有助于制定逃生计划。',
    speaking: 'Give three clear instructions to a friend who is caught in a rip current.',
    vocab: [['offshore', '/ˌɔːfˈʃɔːr/', 'adv.', '向离岸方向'], ['exhaustion', '/ɪɡˈzɔːstʃən/', 'n.', '精疲力竭'], ['parallel', '/ˈpærəlel/', 'adj.', '平行的']],
  },
  {
    id: 'noaa-estuary-nursery', title: 'Where Rivers Meet the Sea', titleZh: '河流与海洋相遇的地方', topic: '海洋与环境', level: 'L2',
    source: ['NOAA National Ocean Service', 'What is an estuary?', 'https://oceanservice.noaa.gov/facts/estuary.html'],
    sentences: [
      'An estuary is a partly enclosed coastal area where freshwater mixes with saltwater from the ocean.',
      'Changing tides create a dynamic environment with shifting salinity, sediment, and water levels.',
      'Marshes, seagrass, mudflats, and shallow channels provide food and shelter for many species.',
      'Young fish and shellfish often use estuaries as protected nursery habitats.',
      'These places can also filter runoff, store carbon, reduce erosion, and soften some storm impacts.',
      'Ports and communities frequently develop nearby because estuaries connect land, rivers, and sea travel.',
      'The same location can support wildlife, jobs, recreation, and protection from coastal hazards.',
      'Protecting an estuary requires managing activities both along the coast and far upstream.',
    ],
    guideZh: '听出淡水与海水混合后形成的生态功能，以及上游活动为何会影响河口。',
    keyIdeaZh: '河口连接陆地、河流和海洋，同时承担育幼、过滤和海岸保护等多重功能。',
    translationZh: '幼鱼和贝类经常把河口作为受到保护的育幼栖息地。',
    writingZh: '同一个地方可以同时支持野生动物、工作和休闲。',
    speaking: 'Explain two benefits an estuary can provide to nature or people.',
    vocab: [['estuary', '/ˈestʃueri/', 'n.', '河口湾'], ['salinity', '/səˈlɪnəti/', 'n.', '盐度'], ['upstream', '/ˌʌpˈstriːm/', 'adv.', '向上游，在上游']],
  },
  {
    id: 'noaa-sea-level', title: 'Sea Level Is Both Global and Local', titleZh: '海平面既是全球问题，也是地方问题', topic: '气候与城市', level: 'L3',
    source: ['NOAA National Ocean Service', 'Is sea level rising?', 'https://oceanservice.noaa.gov/facts/sealevel.html'],
    sentences: [
      'Global average sea level rises when ocean water warms and expands and when land ice melts.',
      'Local sea level can change differently because land may sink, rise, or move after geological events.',
      'Ocean currents, winds, tides, and regional climate patterns also affect what a tide gauge records.',
      'A global trend therefore does not produce exactly the same number along every coastline.',
      'Satellites measure broad ocean height, while long-running coastal gauges provide detailed local histories.',
      'Communities combine both kinds of evidence when they plan roads, drainage, buildings, and emergency routes.',
      'Good adaptation begins with local measurements placed inside a reliable global picture.',
      'The distinction between global and local change improves decisions without denying either scale.',
    ],
    guideZh: '区分 global average 与 local sea level，并记录卫星和验潮仪各自提供的证据。',
    keyIdeaZh: '全球海平面上升趋势会因陆地运动和区域海洋条件而在各地呈现不同速度。',
    translationZh: '因此，全球趋势不会在每一段海岸线上产生完全相同的数字。',
    writingZh: '良好的适应始于可靠的地方测量。',
    speaking: 'Why should a coastal city use both global and local sea-level information?',
    vocab: [['expand', '/ɪkˈspænd/', 'v.', '膨胀'], ['gauge', '/ɡeɪdʒ/', 'n.', '测量仪器'], ['adaptation', '/ˌædæpˈteɪʃn/', 'n.', '适应措施']],
  },
  {
    id: 'noaa-weather-climate', title: 'Weather Is Today; Climate Is the Pattern', titleZh: '天气描述今天，气候描述长期模式', topic: '气候与城市', level: 'L1',
    source: ['NOAA National Ocean Service', 'What is the difference between weather and climate?', 'https://oceanservice.noaa.gov/facts/weather_climate.html'],
    sentences: [
      'Weather describes short-term conditions such as today’s temperature, rain, wind, or cloud cover.',
      'Climate describes patterns and ranges observed in a region over much longer periods.',
      'A cold morning does not disprove a warming climate, just as one hot afternoon cannot define it.',
      'Scientists study many measurements across decades to identify changes in averages and extremes.',
      'Weather forecasts help people decide what to wear or whether to change tomorrow’s plans.',
      'Climate information helps communities design buildings, manage water, and prepare for long-term risks.',
      'The two ideas use related observations but answer questions on different timescales.',
      'Choosing the correct timescale prevents a single unusual day from becoming a misleading conclusion.',
    ],
    guideZh: '用 short-term、long-term 和 timescale 三个线索区分天气与气候的用途。',
    keyIdeaZh: '天气和气候使用相关观测，但回答的是不同时间尺度的问题。',
    translationZh: '科学家研究跨越数十年的大量测量，以识别平均值和极端情况的变化。',
    writingZh: '这两个概念回答不同时间尺度的问题。',
    speaking: 'Give one weather question and one climate question about your city.',
    vocab: [['condition', '/kənˈdɪʃn/', 'n.', '状况'], ['decade', '/ˈdekeɪd/', 'n.', '十年'], ['timescale', '/ˈtaɪmskeɪl/', 'n.', '时间尺度']],
  },
]
