export const SOCIETY_SEEDS = [
  {
    id: 'nist-strong-passwords', title: 'A Strong Password Is Long and Unique', titleZh: '强密码首先要长而且独特', topic: '科技与安全', level: 'L1',
    source: ['National Institute of Standards and Technology', 'How Do I Create a Good Password?', 'https://www.nist.gov/cybersecurity/how-do-i-create-good-password'],
    sentences: [
      'A password protects an account only when an attacker cannot easily guess or reuse it.',
      'Length matters because every additional character can greatly increase the number of possible combinations.',
      'A long passphrase made from unrelated words may be easier to remember than a short complicated pattern.',
      'Every important account should have a unique password so one breach does not unlock several services.',
      'A password manager can create and store strong credentials without requiring perfect human memory.',
      'Multi-factor authentication adds another barrier when a password is stolen.',
      'Changing a good password constantly is less useful than replacing it after compromise or suspected exposure.',
      'Good security reduces repeated decisions by building strong defaults into everyday account use.',
    ],
    guideZh: '听出 length、unique、password manager、MFA 四层策略，并理解频繁改密码并非核心。',
    keyIdeaZh: '长且独特的密码配合密码管理器和多因素认证，比复杂但重复的短密码更可靠。',
    translationZh: '每个重要账号都应该使用独特密码，这样一次泄露就不会解锁多个服务。',
    writingZh: '良好的安全措施会减少重复决策。',
    speaking: 'Explain why reusing one very strong password is still risky.',
    vocab: [['passphrase', '/ˈpæsf reɪz/', 'n.', '密码短语'], ['credential', '/krəˈdenʃl/', 'n.', '身份凭据'], ['compromise', '/ˈkɑːmprəmaɪz/', 'n.', '安全失陷']],
  },
  {
    id: 'nist-phishing-signals', title: 'Phishing Tries to Borrow Your Trust', titleZh: '网络钓鱼试图借用你的信任', topic: '科技与安全', level: 'L2',
    source: ['National Institute of Standards and Technology', 'Phishing', 'https://www.nist.gov/itl/smallbusinesscyber/guidance-topic/phishing'],
    sentences: [
      'Phishing messages imitate a trusted person or organization to make a request feel legitimate.',
      'They may create urgency, fear, curiosity, or excitement so the receiver acts before checking details.',
      'A familiar logo and sender name can be copied, while the underlying address or link points elsewhere.',
      'Instead of using a message link, open the known website or contact the sender through a separate channel.',
      'Unexpected attachments, payment changes, password requests, and unusual secrecy deserve extra verification.',
      'Reporting a suspicious message helps an organization protect other people who received it.',
      'The safest habit is to slow down precisely when a message insists there is no time.',
      'Phishing defense combines technical filters with a human process for verifying unusual requests.',
    ],
    guideZh: '识别 urgency、copied identity、separate channel 三个关键信号和应对动作。',
    keyIdeaZh: '钓鱼攻击利用情绪和信任，最有效的人类防线是在紧急时停下来独立核验。',
    translationZh: '不要使用消息中的链接，而应打开已知网站或通过另一条渠道联系发送者。',
    writingZh: '最安全的习惯是在消息催促时放慢速度。',
    speaking: 'Describe how you would verify an urgent payment request from a familiar colleague.',
    vocab: [['legitimate', '/lɪˈdʒɪtɪmət/', 'adj.', '合法可信的'], ['underlying', '/ˌʌndərˈlaɪɪŋ/', 'adj.', '底层的，实际的'], ['verification', '/ˌverɪfɪˈkeɪʃn/', 'n.', '核验']],
  },
  {
    id: 'nist-multi-factor', title: 'One More Factor Changes an Attack', titleZh: '多一个认证因素，就能改变攻击难度', topic: '科技与安全', level: 'L2',
    source: ['National Institute of Standards and Technology', 'Multi-Factor Authentication', 'https://www.nist.gov/itl/smallbusinesscyber/guidance-topic/multi-factor-authentication'],
    sentences: [
      'Authentication asks a user to prove that an account really belongs to them.',
      'A password is one factor based on something the user knows.',
      'A security key, authenticator, device, or biometric check can provide a different kind of factor.',
      'Multi-factor authentication requires more than one factor before granting access.',
      'A stolen password is then less useful because the attacker still lacks another required proof.',
      'Some methods resist phishing better than one-time codes sent by text message.',
      'The best available method should protect email, finance, administration, and other high-value accounts first.',
      'Adding a second factor changes a single stolen secret from complete access into only one part of the puzzle.',
    ],
    guideZh: '区分 something you know 与其他 factor，并理解为什么不同方法抗钓鱼能力不同。',
    keyIdeaZh: '多因素认证让被盗密码不再等同于完整访问权限。',
    translationZh: '多因素认证要求提供不止一种因素，之后才授予访问权限。',
    writingZh: '高价值账号应该最先受到保护。',
    speaking: 'Which accounts would you protect with multi-factor authentication first, and why?',
    vocab: [['authentication', '/ɔːˌθentɪˈkeɪʃn/', 'n.', '身份认证'], ['biometric', '/ˌbaɪoʊˈmetrɪk/', 'adj.', '生物特征的'], ['grant', '/ɡrænt/', 'v.', '授予']],
  },
  {
    id: 'nist-si-units', title: 'Shared Units Make Measurements Travel', titleZh: '统一单位让测量结果跨越边界', topic: '科学与社会', level: 'L2',
    source: ['National Institute of Standards and Technology', 'SI Units', 'https://www.nist.gov/pml/owm/metric-si/si-units'],
    sentences: [
      'A measurement is useful only when other people understand the unit and can reproduce the result.',
      'The International System of Units provides a shared language for length, mass, time, temperature, and more.',
      'Seven base units support many derived units used in science, engineering, medicine, and trade.',
      'Modern definitions connect units to stable physical constants rather than to one fragile object.',
      'Calibration compares an instrument with a trusted reference so its readings remain reliable.',
      'A small unit error can become a large safety, manufacturing, or financial problem.',
      'Shared standards allow a component measured in one country to fit a system built in another.',
      'Metrology may seem invisible, but it supports confidence in nearly every technical number people use.',
    ],
    guideZh: '听出 unit、constant、calibration、standard 的关系，理解统一测量如何支撑协作。',
    keyIdeaZh: '国际单位和校准体系让不同地点的测量具有可比较性和可信度。',
    translationZh: '现代定义把单位与稳定的物理常数联系起来，而不是依赖一个脆弱物体。',
    writingZh: '共享标准让不同国家制造的部件能够配合。',
    speaking: 'Give an example of a problem that could result from inconsistent measurement units.',
    vocab: [['derived', '/dɪˈraɪvd/', 'adj.', '派生的'], ['calibration', '/ˌkælɪˈbreɪʃn/', 'n.', '校准'], ['metrology', '/məˈtrɑːlədʒi/', 'n.', '计量学']],
  },
  {
    id: 'usgs-water-cycle', title: 'The Water Cycle Has Stores as Well as Motion', titleZh: '水循环既有流动，也有储存', topic: '地球与环境', level: 'L2',
    source: ['U.S. Geological Survey', 'Water Cycle', 'https://www.usgs.gov/special-topics/water-science-school/water-cycle'],
    sentences: [
      'The water cycle describes water moving among the atmosphere, surface, ground, ice, ocean, and living things.',
      'Evaporation and plant transpiration send water vapor into the air, where it can condense into clouds.',
      'Precipitation returns water as rain, snow, or other forms depending on atmospheric conditions.',
      'Some water runs across land, some enters soil and rock, and some remains stored in ice or lakes.',
      'Groundwater may move slowly for years while a storm runoff channel changes within minutes.',
      'People alter the cycle through pumping, dams, paved surfaces, land cover, and water use.',
      'The cycle is not a simple circle because water follows many paths and waits in stores for different lengths of time.',
      'Understanding both movement and storage helps communities manage floods, drought, supply, and ecosystems.',
    ],
    guideZh: '不要把水循环只画成圆圈，要听出多条路径、不同储存位置和不同时间尺度。',
    keyIdeaZh: '水在多条路径中流动，并会在地下水、冰和湖泊等位置停留不同时间。',
    translationZh: '一部分水流过地表，一部分进入土壤和岩石，还有一部分储存在冰或湖泊中。',
    writingZh: '水不会沿着一个简单的圆圈流动。',
    speaking: 'Follow one drop of rain through two different possible paths in the water cycle.',
    vocab: [['transpiration', '/ˌtrænspəˈreɪʃn/', 'n.', '蒸腾作用'], ['precipitation', '/prɪˌsɪpɪˈteɪʃn/', 'n.', '降水'], ['groundwater', '/ˈɡraʊndwɔːtər/', 'n.', '地下水']],
  },
  {
    id: 'usgs-earthquake-science', title: 'An Earthquake Begins with Stored Stress', titleZh: '地震始于积累的应力', topic: '地球与安全', level: 'L3',
    source: ['U.S. Geological Survey', 'The Science of Earthquakes', 'https://www.usgs.gov/programs/earthquake-hazards/science-earthquakes'],
    sentences: [
      'Tectonic plates move slowly, but friction can lock sections of a fault for long periods.',
      'Stress builds until the rocks slip, releasing energy that travels outward as seismic waves.',
      'The point where rupture begins underground is the hypocenter, while the epicenter lies above it at the surface.',
      'Instruments record ground motion and help scientists locate an event and estimate its magnitude.',
      'Magnitude describes earthquake size, while shaking intensity varies from place to place.',
      'Distance, depth, soil, building design, and local geology all influence the damage people experience.',
      'Scientists can estimate long-term hazard, but they cannot reliably predict the exact time of a future earthquake.',
      'Prepared buildings and practiced actions turn scientific knowledge into reduced risk.',
    ],
    guideZh: '按 locked fault、stress、slip、seismic waves 的过程理解地震，并区分 magnitude 与 intensity。',
    keyIdeaZh: '地震规模与当地震感和损害不是同一概念，风险还取决于环境与建筑。',
    translationZh: '仪器记录地面运动，帮助科学家定位事件并估算其震级。',
    writingZh: '科学家可以估计长期危险。',
    speaking: 'Explain why the same earthquake can cause different levels of shaking in two cities.',
    vocab: [['fault', '/fɔːlt/', 'n.', '断层'], ['hypocenter', '/ˈhaɪpəʊsentər/', 'n.', '震源'], ['magnitude', '/ˈmæɡnɪtuːd/', 'n.', '震级']],
  },
  {
    id: 'usgs-volcano-alerts', title: 'A Volcano Alert Communicates Uncertainty', titleZh: '火山预警也在传达不确定性', topic: '地球与安全', level: 'L3',
    source: ['U.S. Geological Survey', 'Volcano Hazards Program', 'https://www.usgs.gov/programs/VHP'],
    sentences: [
      'Volcano observatories monitor earthquakes, ground deformation, gas, heat, and visual changes around active volcanoes.',
      'No single signal proves that an eruption will occur because volcanic systems can change without erupting.',
      'Scientists compare several observations with the volcano’s history to judge whether unrest is increasing.',
      'Alert levels summarize current conditions and help public agencies coordinate decisions.',
      'An alert is not a promise of a specific event at an exact time.',
      'Ash, lava, gases, mudflows, and landslides create different hazards that may reach different areas.',
      'Clear updates should describe evidence, uncertainty, possible impacts, and recommended actions together.',
      'Monitoring reduces surprise, while community planning turns warning time into safer movement and communication.',
    ],
    guideZh: '听出多种监测信号，并理解 alert level 是对当前状态的概括，不是精确预言。',
    keyIdeaZh: '火山监测通过多种证据管理不确定性，并为公共行动争取时间。',
    translationZh: '预警不是对某个事件将在准确时间发生的承诺。',
    writingZh: '监测能够减少意外。',
    speaking: 'What information should a clear volcano update include besides an alert level?',
    vocab: [['deformation', '/ˌdiːfɔːrˈmeɪʃn/', 'n.', '形变'], ['unrest', '/ʌnˈrest/', 'n.', '异常活动'], ['observatory', '/əbˈzɜːrvətɔːri/', 'n.', '观测站']],
  },
  {
    id: 'nps-leave-no-trace', title: 'Leave No Trace Is a Decision System', titleZh: '无痕山林是一套决策方法', topic: '旅行与自然', level: 'L2',
    source: ['National Park Service', 'Leave No Trace Seven Principles', 'https://www.nps.gov/articles/leave-no-trace-seven-principles.htm'],
    sentences: [
      'Leave No Trace principles help visitors reduce their impact while enjoying parks and other outdoor places.',
      'Planning ahead prevents emergencies and helps people bring the right food, clothing, and waste containers.',
      'Durable surfaces concentrate travel where footsteps are less likely to damage fragile plants or soil.',
      'Visitors should pack out waste, leave natural objects, and avoid changing a site for convenience.',
      'Wildlife stays safer when people watch from a distance and keep food secure.',
      'Quiet, respectful behavior also protects the experience of other visitors.',
      'The principles are not only cleanup rules; they guide choices before, during, and after a trip.',
      'Responsible access keeps an outdoor place enjoyable without requiring that nobody visit it.',
    ],
    guideZh: '把原则理解为出发前、旅行中和离开后的决策系统，而不只是捡垃圾。',
    keyIdeaZh: '无痕理念通过提前规划和现场选择，在开放自然体验的同时降低影响。',
    translationZh: '游客应该带走垃圾、保留自然物品原状，不要为了方便改变场地。',
    writingZh: '这些原则在旅行前、中、后都能指导选择。',
    speaking: 'Choose two Leave No Trace principles and apply them to a weekend trip.',
    vocab: [['durable', '/ˈdʊrəbl/', 'adj.', '耐久的'], ['fragile', '/ˈfrædʒl/', 'adj.', '脆弱的'], ['concentrate', '/ˈkɑːnsntreɪt/', 'v.', '集中']],
  },
  {
    id: 'nps-night-skies', title: 'Darkness Is a Natural Resource', titleZh: '黑暗也是一种自然资源', topic: '旅行与自然', level: 'L2',
    source: ['National Park Service', 'Night Skies', 'https://www.nps.gov/subjects/nightskies/index.htm'],
    sentences: [
      'A naturally dark night sky reveals stars, planets, the Milky Way, and patterns used by cultures for generations.',
      'Artificial light can brighten the sky far beyond the place where a lamp is installed.',
      'Excess light may waste energy, disturb wildlife behavior, affect human experience, and hide astronomical detail.',
      'Useful outdoor lighting points downward, limits brightness, uses suitable color, and operates only when needed.',
      'Dark-sky protection does not require turning off every light or reducing safety.',
      'It asks designers to put the right amount of light in the right place at the right time.',
      'A well-designed fixture can improve visibility while sending less light into the sky.',
      'Protecting darkness preserves science, wildlife, energy, cultural heritage, and a shared view of the universe.',
    ],
    guideZh: '记录光污染的多种影响，并听出方向、亮度、色温和时间四个设计变量。',
    keyIdeaZh: '保护夜空不是拒绝照明，而是让合适的光在合适时间照到合适位置。',
    translationZh: '有用的户外照明应向下照射、限制亮度、使用合适颜色，并只在需要时运行。',
    writingZh: '设计良好的灯具能够改善能见度。',
    speaking: 'How could your neighborhood reduce sky glow without making streets feel unsafe?',
    vocab: [['artificial', '/ˌɑːrtɪˈfɪʃl/', 'adj.', '人工的'], ['fixture', '/ˈfɪkstʃər/', 'n.', '灯具，固定装置'], ['heritage', '/ˈherɪtɪdʒ/', 'n.', '文化遗产']],
  },
]
