export const SPACE_SEEDS = [
  {
    id: 'nasa-moon-facts', title: 'Why We Always See the Same Side of the Moon', titleZh: '为什么我们总看到月球的同一面', topic: '太空与科学', level: 'L2',
    source: ['NASA Science', 'Moon Facts', 'https://science.nasa.gov/moon/facts/'],
    sentences: [
      'The Moon travels around Earth while also turning slowly on its own axis.',
      'One lunar rotation takes almost the same amount of time as one orbit around our planet.',
      'Because these two motions stay synchronized, the same lunar hemisphere usually faces Earth.',
      'The far side is not permanently dark; it receives sunlight during every lunar month.',
      'Changing sunlight creates the phases we see, from a thin crescent to a full Moon.',
      'Impact craters, cooled lava, and ancient ice make the lunar surface a record of solar-system history.',
      'Synchronized motion explains our familiar view without implying that the Moon has stopped rotating.',
      'Understanding this relationship turns an everyday sight into a clear lesson about motion and perspective.',
    ],
    guideZh: '听文章时区分 rotation、orbit 和 phase，理解两个周期同步后产生的视觉结果。',
    keyIdeaZh: '月球自转与绕地公转周期接近，因此同一面长期朝向地球。',
    translationZh: '月球背面并非永远黑暗；它在每个阴历月都会接受阳光。',
    writingZh: '同步运动解释了我们熟悉的景象。',
    speaking: 'Explain why the far side of the Moon is not the same as a permanently dark side.',
    vocab: [['synchronized', '/ˈsɪŋkrənaɪzd/', 'adj.', '同步的'], ['hemisphere', '/ˈhemɪsfɪr/', 'n.', '半球'], ['crescent', '/ˈkresnt/', 'n.', '新月形']],
  },
  {
    id: 'nasa-mars-seasons', title: 'A Day on Mars Feels Familiar, but a Year Does Not', titleZh: '火星的一天很熟悉，一年却很不同', topic: '太空与科学', level: 'L2',
    source: ['NASA Science', 'Mars Facts', 'https://science.nasa.gov/mars/facts/'],
    sentences: [
      'Mars completes one rotation in about 24.6 hours, so a Martian day is close to an Earth day.',
      'Scientists call that day a sol, a useful word when they plan rover operations.',
      'A Martian year is much longer because Mars follows a wider path around the Sun.',
      'It takes about 687 Earth days for Mars to complete a single orbit.',
      'Mars also has seasons because its axis is tilted in a way that resembles Earth.',
      'However, its elliptical orbit makes those seasons unequal in length and more extreme in some regions.',
      'A familiar daily rhythm can therefore exist inside a calendar that feels completely different.',
      'Mission teams must translate between sols and Earth dates when they schedule science and communicate results.',
    ],
    guideZh: '抓住 day、sol、year 和 season 四个时间概念，比较火星与地球的相似和差异。',
    keyIdeaZh: '火星日接近地球日，但更长的公转轨道让火星年和季节明显不同。',
    translationZh: '火星绕太阳完成一周大约需要687个地球日。',
    writingZh: '熟悉的日常节奏可能存在于完全不同的日历中。',
    speaking: 'Which would be harder to adjust to on Mars: the length of a day or the length of a year?',
    vocab: [['sol', '/sɑːl/', 'n.', '火星日'], ['elliptical', '/ɪˈlɪptɪkl/', 'adj.', '椭圆形的'], ['rotation', '/roʊˈteɪʃn/', 'n.', '自转']],
  },
  {
    id: 'nasa-earth-atmosphere', title: 'Earth Is More Than a Blue Surface', titleZh: '地球不只是一颗蓝色星球', topic: '太空与科学', level: 'L1',
    source: ['NASA Science', 'Earth Facts', 'https://science.nasa.gov/earth/facts/'],
    sentences: [
      'From space, Earth looks blue because oceans cover most of its surface.',
      'Liquid water is only one part of the system that makes our planet unusual.',
      'The atmosphere contains gases that support life and help regulate surface temperature.',
      'A magnetic field also deflects many charged particles arriving from the Sun.',
      'Land, ocean, air, ice, and living things constantly exchange energy and material.',
      'A change in one part of this connected system can influence many other parts.',
      'Earth stays habitable through relationships among water, air, rock, sunlight, and life.',
      'Seeing the planet as a system helps scientists study both local events and global change.',
    ],
    guideZh: '不要只听“蓝色星球”的描述，重点记录水、大气、磁场和生命之间的联系。',
    keyIdeaZh: '地球宜居不是单一条件造成的，而是多个系统长期相互作用的结果。',
    translationZh: '磁场还能偏转许多来自太阳的带电粒子。',
    writingZh: '地球通过水、空气、岩石、阳光和生命之间的联系保持宜居。',
    speaking: 'Choose one Earth system and explain how it connects with another system.',
    vocab: [['atmosphere', '/ˈætməsfɪr/', 'n.', '大气层'], ['deflect', '/dɪˈflekt/', 'v.', '使偏转'], ['habitable', '/ˈhæbɪtəbl/', 'adj.', '适宜居住的']],
  },
  {
    id: 'nasa-sun-energy', title: 'The Sun Holds the Solar System Together', titleZh: '太阳如何维系整个太阳系', topic: '太空与科学', level: 'L2',
    source: ['NASA Science', 'Sun Facts', 'https://science.nasa.gov/sun/facts/'],
    sentences: [
      'The Sun is an ordinary star in one sense, yet it dominates our local neighborhood in space.',
      'Its gravity keeps planets, dwarf planets, asteroids, and comets moving in stable paths.',
      'Deep inside the Sun, nuclear fusion combines hydrogen and releases enormous amounts of energy.',
      'That energy takes time to travel outward before reaching Earth as light and heat.',
      'Sunlight powers photosynthesis, influences weather, and supports almost every food chain on our planet.',
      'Solar activity can also disturb satellites, radio communication, navigation, and electrical systems.',
      'The Sun is both a steady source of life-giving energy and a changing space-weather environment.',
      'Studying it helps scientists understand stars while protecting technology used in daily life.',
    ],
    guideZh: '按 gravity、fusion、sunlight、space weather 的顺序理解太阳的四种作用。',
    keyIdeaZh: '太阳既为生命提供能量，也通过太空天气影响现代技术。',
    translationZh: '这些能量向外传播需要时间，之后才以光和热的形式到达地球。',
    writingZh: '太阳既是稳定的能量来源，也是不断变化的太空天气环境。',
    speaking: 'Describe one way the Sun supports life and one way it can disrupt technology.',
    vocab: [['fusion', '/ˈfjuːʒn/', 'n.', '核聚变'], ['dominate', '/ˈdɑːmɪneɪt/', 'v.', '支配，占主导'], ['disturb', '/dɪˈstɜːrb/', 'v.', '干扰']],
  },
  {
    id: 'nasa-venus-greenhouse', title: 'Venus Shows the Power of an Atmosphere', titleZh: '金星展示了大气层的力量', topic: '太空与科学', level: 'L3',
    source: ['NASA Science', 'Venus Facts', 'https://science.nasa.gov/venus/venus-facts/'],
    sentences: [
      'Venus is similar to Earth in size, but its surface conditions are dramatically different.',
      'A thick atmosphere made mostly of carbon dioxide traps heat with an intense greenhouse effect.',
      'Surface temperatures are high enough to melt lead, even though Venus is not the closest planet to the Sun.',
      'Clouds of sulfuric acid hide the surface from ordinary visible-light cameras.',
      'Radar instruments can look through those clouds and map mountains, plains, and volcanic features.',
      'Venus rotates very slowly and in the opposite direction from most planets.',
      'Similar size does not guarantee a similar climate when atmospheric history develops differently.',
      'By studying Venus, scientists test ideas about climate, geology, and the evolution of rocky worlds.',
    ],
    guideZh: '关注 similar in size 与 dramatically different 的对比，并记录大气如何改变行星表面。',
    keyIdeaZh: '行星大小相近并不意味着气候相近，大气演化会造成巨大差异。',
    translationZh: '硫酸云层使普通的可见光相机无法看到金星表面。',
    writingZh: '相似的大小并不能保证相似的气候。',
    speaking: 'Why is Venus useful for testing ideas about planets and climate?',
    vocab: [['intense', '/ɪnˈtens/', 'adj.', '强烈的'], ['sulfuric', '/sʌlˈfjʊrɪk/', 'adj.', '硫酸的'], ['evolution', '/ˌevəˈluːʃn/', 'n.', '演化']],
  },
  {
    id: 'nasa-jupiter-storms', title: 'Jupiter Is a World of Motion', titleZh: '木星是一颗不断运动的世界', topic: '太空与科学', level: 'L2',
    source: ['NASA Science', 'Jupiter Facts', 'https://science.nasa.gov/jupiter/jupiter-facts/'],
    sentences: [
      'Jupiter is the largest planet in our solar system and is made mostly of hydrogen and helium.',
      'It has no solid surface like Earth, although pressure increases greatly deeper inside the planet.',
      'Fast rotation stretches clouds into colorful bands that move in different directions.',
      'The Great Red Spot is a giant storm that has been observed for generations.',
      'Jupiter also has a powerful magnetic field and a large family of moons.',
      'Some of those moons contain ice, volcanoes, or possible oceans beneath their surfaces.',
      'The planet and its moons form a complex system rather than a single isolated object.',
      'Exploring that system helps scientists study storms, magnetic environments, and possible habitats beyond Earth.',
    ],
    guideZh: '听出木星本体的气体、风暴和磁场，再把注意力转向它的卫星系统。',
    keyIdeaZh: '研究木星需要把行星、磁场和众多卫星看成一个复杂系统。',
    translationZh: '大红斑是一场已经被观测了数代人的巨型风暴。',
    writingZh: '这颗行星及其卫星构成了一个复杂系统。',
    speaking: 'Which feature of Jupiter or its moons would you most like to investigate, and why?',
    vocab: [['hydrogen', '/ˈhaɪdrədʒən/', 'n.', '氢'], ['magnetic', '/mæɡˈnetɪk/', 'adj.', '磁性的'], ['isolated', '/ˈaɪsəleɪtɪd/', 'adj.', '孤立的']],
  },
  {
    id: 'nasa-saturn-rings', title: 'Saturn’s Rings Are Bright but Temporary', titleZh: '土星环耀眼，却并非永恒', topic: '太空与科学', level: 'L2',
    source: ['NASA Science', 'Saturn Facts', 'https://science.nasa.gov/saturn/facts/'],
    sentences: [
      'Saturn is famous for rings that can be seen even with a modest telescope.',
      'The rings contain countless pieces of ice and rock, ranging from dust-sized grains to much larger chunks.',
      'They appear solid from far away, but wide gaps separate many of their particles.',
      'Gravity from Saturn and its moons shapes ring edges, waves, and narrow divisions.',
      'Some material falls gradually into the planet, while collisions continue to change the ring system.',
      'Scientists therefore do not expect the rings to remain exactly as they are forever.',
      'A beautiful structure can look permanent on a human timescale while still evolving astronomically.',
      'Saturn offers a visible laboratory for studying gravity, collisions, and change across a planetary system.',
    ],
    guideZh: '先想象远看像实体的土星环，再听清粒子、间隙、引力和变化之间的关系。',
    keyIdeaZh: '土星环由大量运动中的冰石颗粒组成，并会在漫长时间里持续演化。',
    translationZh: '土星及其卫星的引力塑造了环的边缘、波纹和狭窄分隔。',
    writingZh: '美丽的结构在人类时间尺度上可能显得永恒。',
    speaking: 'Why can Saturn’s rings look solid even though they are made of separate particles?',
    vocab: [['particle', '/ˈpɑːrtɪkl/', 'n.', '颗粒'], ['division', '/dɪˈvɪʒn/', 'n.', '分隔'], ['astronomically', '/ˌæstrəˈnɑːmɪkli/', 'adv.', '在天文尺度上']],
  },
  {
    id: 'nasa-asteroid-records', title: 'Asteroids Preserve an Ancient Record', titleZh: '小行星保存着远古记录', topic: '太空与科学', level: 'L3',
    source: ['NASA Science', 'Asteroid Facts', 'https://science.nasa.gov/solar-system/asteroids/facts/'],
    sentences: [
      'Asteroids are rocky remnants left from the formation of the solar system about 4.6 billion years ago.',
      'Most orbit the Sun between Mars and Jupiter, but others follow paths that approach Earth.',
      'Their shapes are often irregular because many are too small for gravity to make them round.',
      'Some asteroids are loose collections of material held together weakly by gravity.',
      'Spacecraft can measure their composition, photograph their surfaces, and sometimes return samples to Earth.',
      'Those samples preserve chemical clues that have been altered or erased on active planets.',
      'A small object can carry evidence about conditions that existed before Earth fully formed.',
      'Tracking nearby asteroids also improves knowledge that can support long-term planetary defense.',
    ],
    guideZh: '抓住 remnants、samples、clues 三个词，理解小行星为何像太阳系的历史档案。',
    keyIdeaZh: '小行星样本保留了活跃行星上可能已经消失的早期化学线索。',
    translationZh: '有些小行星是由引力松散维系在一起的物质集合。',
    writingZh: '一个小天体也能携带地球形成之前的证据。',
    speaking: 'Give one scientific reason and one safety reason for studying asteroids.',
    vocab: [['remnant', '/ˈremnənt/', 'n.', '残余物'], ['irregular', '/ɪˈreɡjələr/', 'adj.', '不规则的'], ['composition', '/ˌkɑːmpəˈzɪʃn/', 'n.', '组成成分']],
  },
  {
    id: 'nasa-rocky-exoplanets', title: 'A Rocky Planet Is Only the Beginning', titleZh: '发现岩石行星只是开始', topic: '太空与科学', level: 'L3',
    source: ['NASA Science', 'Terrestrial Exoplanets', 'https://science.nasa.gov/exoplanets/terrestrial/'],
    sentences: [
      'Astronomers call planets dominated by rock or iron terrestrial planets.',
      'Finding a world close to Earth in size does not automatically make it habitable.',
      'Researchers must also investigate its orbit, temperature, atmosphere, star, and possible surface conditions.',
      'A planet may be rocky while remaining far too hot, cold, or exposed to radiation for familiar life.',
      'Telescopes study tiny changes in starlight to estimate a planet’s size and atmospheric chemistry.',
      'Each measurement carries uncertainty, so several methods are stronger than one signal alone.',
      'The word Earth-like should describe specific evidence rather than serve as a promise of another Earth.',
      'Careful language helps the public understand both the excitement and limits of exoplanet discoveries.',
    ],
    guideZh: '注意文章如何限制 Earth-like 这个说法，并列出判断宜居性需要的多种证据。',
    keyIdeaZh: '岩石结构和地球大小只是线索，不能单独证明一颗行星适宜生命存在。',
    translationZh: '一颗行星可能是岩石构成的，却仍然过热、过冷或暴露在强辐射下。',
    writingZh: '“类地”一词应该描述具体证据。',
    speaking: 'What evidence would you want before calling an exoplanet Earth-like?',
    vocab: [['terrestrial', '/təˈrestriəl/', 'adj.', '类地的，陆地的'], ['habitable', '/ˈhæbɪtəbl/', 'adj.', '适宜居住的'], ['uncertainty', '/ʌnˈsɜːrtnti/', 'n.', '不确定性']],
  },
]
